"""initial schema

Revision ID: bfd02983839b
Revises: 
Create Date: 2026-08-01 07:28:10.435899
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bfd02983839b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('badges',
    sa.Column('badge_id', sa.UUID(), nullable=False),
    sa.Column('badge_name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('criteria', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('icon_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('badge_id')
    )
    op.create_table('roles',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('role_name', sa.Enum('STUDENT', 'TEACHER', 'SCHOOL_ADMIN', 'SUPER_ADMIN', name='rolename'), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('role_id')
    )
    op.create_table('schools',
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('school_code', sa.String(), nullable=False),
    sa.Column('school_name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('pincode', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('school_id')
    )
    op.create_index(op.f('ix_schools_school_code'), 'schools', ['school_code'], unique=True)
    op.create_table('school_trust_factors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('factor_type', sa.String(), nullable=False),
    sa.Column('factor_score', sa.Float(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.school_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('school_trust_score',
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('current_trust_score', sa.Float(), nullable=False),
    sa.Column('last_calculated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.school_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('school_id')
    )
    op.create_table('trust_score_history_school',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.school_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email_encrypted', sa.String(), nullable=False),
    sa.Column('email_hash', sa.String(), nullable=False),
    sa.Column('phone_encrypted', sa.String(), nullable=True),
    sa.Column('phone_hash', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('profile_image', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'DISABLED', 'SUSPENDED', name='userstatus'), nullable=False),
    sa.Column('trust_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.role_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.school_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email_encrypted'), 'users', ['email_encrypted'], unique=True)
    op.create_index(op.f('ix_users_email_hash'), 'users', ['email_hash'], unique=True)
    op.create_index(op.f('ix_users_phone_encrypted'), 'users', ['phone_encrypted'], unique=True)
    op.create_index(op.f('ix_users_phone_hash'), 'users', ['phone_hash'], unique=True)
    op.create_table('challenges',
    sa.Column('challenge_id', sa.UUID(), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.school_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('challenge_id')
    )
    op.create_table('device_approvals',
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.String(length=100), nullable=False),
    sa.Column('device_name', sa.String(length=100), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('request_id')
    )
    op.create_index(op.f('ix_device_approvals_status'), 'device_approvals', ['status'], unique=False)
    op.create_index(op.f('ix_device_approvals_user_id'), 'device_approvals', ['user_id'], unique=False)
    op.create_table('devices',
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('device_name', sa.String(), nullable=False),
    sa.Column('os', sa.String(), nullable=True),
    sa.Column('browser', sa.String(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('trusted_device', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('device_id')
    )
    op.create_table('leaderboard',
    sa.Column('leaderboard_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('total_points', sa.Integer(), nullable=False),
    sa.Column('global_rank', sa.Integer(), nullable=True),
    sa.Column('category_rank', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('leaderboard_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('trust_score_history_user',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_badges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('badge_id', sa.UUID(), nullable=False),
    sa.Column('earned_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('points_earned', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['badge_id'], ['badges.badge_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_sessions',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.String(length=100), nullable=False),
    sa.Column('device_name', sa.String(length=100), nullable=False),
    sa.Column('refresh_token_hash', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_active_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index(op.f('ix_user_sessions_is_active'), 'user_sessions', ['is_active'], unique=False)
    op.create_index(op.f('ix_user_sessions_refresh_token_hash'), 'user_sessions', ['refresh_token_hash'], unique=False)
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    op.create_table('login_audit',
    sa.Column('audit_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('login_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('login_method', sa.Enum('EMAIL', 'MOBILE', 'GOOGLE', name='loginmethod'), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('device_id', sa.UUID(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('SUCCESS', 'FAILED', name='loginstatus'), nullable=False),
    sa.Column('failure_reason', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.device_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('audit_id')
    )
    op.create_table('submissions',
    sa.Column('submission_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('challenge_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'APPROVED', 'VERIFIED', 'REJECTED', name='submissionstatus'), nullable=False),
    sa.Column('points_earned', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.challenge_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('submission_id')
    )
    op.create_table('ai_verification',
    sa.Column('verification_id', sa.UUID(), nullable=False),
    sa.Column('submission_id', sa.UUID(), nullable=False),
    sa.Column('ai_score', sa.Float(), nullable=True),
    sa.Column('gps_verified', sa.Boolean(), nullable=False),
    sa.Column('exif_verified', sa.Boolean(), nullable=False),
    sa.Column('duplicate_score', sa.Integer(), nullable=True),
    sa.Column('fraud_score', sa.Integer(), nullable=True),
    sa.Column('final_status', sa.Enum('VERIFIED', 'APPROVED', 'REJECTED', 'PENDING', name='verificationstatus'), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.submission_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verified_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('verification_id'),
    sa.UniqueConstraint('submission_id')
    )
    op.create_table('security_events',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('verification_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='severitylevel'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('resolved_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['verification_id'], ['ai_verification.verification_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('security_events')
    op.drop_table('ai_verification')
    op.drop_table('submissions')
    op.drop_table('login_audit')
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_refresh_token_hash'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_is_active'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_table('user_badges')
    op.drop_table('trust_score_history_user')
    op.drop_table('leaderboard')
    op.drop_table('devices')
    op.drop_index(op.f('ix_device_approvals_user_id'), table_name='device_approvals')
    op.drop_index(op.f('ix_device_approvals_status'), table_name='device_approvals')
    op.drop_table('device_approvals')
    op.drop_table('challenges')
    op.drop_index(op.f('ix_users_phone_hash'), table_name='users')
    op.drop_index(op.f('ix_users_phone_encrypted'), table_name='users')
    op.drop_index(op.f('ix_users_email_hash'), table_name='users')
    op.drop_index(op.f('ix_users_email_encrypted'), table_name='users')
    op.drop_table('users')
    op.drop_table('trust_score_history_school')
    op.drop_table('school_trust_score')
    op.drop_table('school_trust_factors')
    op.drop_index(op.f('ix_schools_school_code'), table_name='schools')
    op.drop_table('schools')
    op.drop_table('roles')
    op.drop_table('badges')
    # ### end Alembic commands ###
